s

diff --git a/.local/bin/wmsel b/.local/bin/wmsel
--- a/.local/bin/wmsel
+++ b/.local/bin/wmsel
@@ -4,10 +4,54 @@
 # and pipe it out
 # to be used upon login to startx with
 
-wms=$(ls /usr/share/xsessions/)
+# deprecated because you can't do defaults
+# wms=$(ls /usr/share/xsessions/ | cut -d '.' -f 1)
+# select wm in ${wms}
+# do wm="${wm}"; break;
+# done
+# echo $wm
 
-select wm in ${wms}
-do wm="${wm}"; break;
-done
+# https://stackoverflow.com/questions/42789273/bash-choose-default-from-case-when-enter-is-pressed-in-a-select-prompt
+# Custom `select` implementation that allows *empty* input.
+# Pass the choices as individual arguments.
+# Output is the chosen item, or "", if the user just pressed ENTER.
+# Example:
+#    choice=$(selectWithDefault 'one' 'two' 'three')
+selectWithDefault() {
 
-echo $wm | cut -d '.' -f 1
+  local item i=0 numItems=$#
+
+  # Print numbered menu items, based on the arguments passed.
+  for item; do         # Short for: for item in "$@"; do
+    printf '%s\n' "$((++i))) $item"
+  done >&2 # Print to stderr, as `select` does.
+
+  # Prompt the user for the index of the desired item.
+  while :; do
+    printf %s "${PS3-#? }" >&2 # Print the prompt string to stderr, as `select` does.
+    read -r index
+    # Make sure that the input is either empty or that a valid index was entered.
+    [[ -z $index ]] && break  # empty input
+    (( index >= 1 && index <= numItems )) 2>/dev/null || { echo "Invalid selection. Please try again." >&2; continue; }
+    break
+  done
+
+  # Output the selected item, if any.
+  [[ -n $index ]] && printf %s "${@: index:1}"
+
+}
+
+wms=$(ls /usr/share/xsessions/ | cut -d '.' -f 1)
+
+# select from list
+opt=$(selectWithDefault $wms)
+# select wm in ${wms}
+# do wm="${wm}"; break;
+# done
+case $opt in
+  '' ) wm='i3'; ;;
+  *  ) wm=$opt; ;;
+esac
+
+# remove .desktop
+echo $wm
