s

diff --git a/.local/bin/setup/setup b/.local/bin/setup/setup
--- a/.local/bin/setup/setup
+++ b/.local/bin/setup/setup
@@ -2,34 +2,37 @@
 #
 # experimental setup script
 
+die() { echo "$*" 1>&2 ; exit 1; }
+warn() { echo "$*" 1>&2 ; }
+
 cd $HOME
 
 # clear out home
-rm -rf $HOME/*
+rm -rf $HOME/* || warn "failed to clear out home directory"
 
 # setup home filesystem
-mkdir $HOME/{coding/iso_store,dl/torrent,docs/org,kb,media/{music,pictures,videos}}
+mkdir $HOME/{coding/iso_store,dl/torrent,docs/org,kb,media/{music,pictures,videos}} || warn "failed to create home directories"
 
 # clone dotfiles
-git clone --bare https://github.com/bcmertz/dotfiles.git $HOME/.cfg
+git clone --bare https://github.com/bcmertz/dotfiles.git $HOME/.cfg || die "failed to clone dotfiles"
 
 # alias git commands and checkout files
 alias cfg='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
-cfg checkout -f
+cfg checkout -f || die "failed to checkout local dotfiles"
 
 # install packages
-sudo pacman -S --needed - < $HOME/.local/share/packages/packages.txt
-yay -S --needed - < $HOME/.local/share/packages/aur-packages.txt
+sudo pacman -Syu yay || die "please manually install yay" # in endeavour os repos
+yay -S --needed - < $HOME/.local/share/packages/packages.txt || warn "failed to install packages"
 
 # suckless utilities
-git clone https://github.com/bcmertz/dmenu.git $HOME/coding/dmenu
+git clone https://github.com/bcmertz/dmenu.git $HOME/coding/dmenu || warn "failed to clone dmenu"
 cd $HOME/coding/dmenu
-sudo make clean install
+sudo make clean install || warn "failed to install dmenu"
 cd $HOME
 
-git clone https://github.com/bcmertz/st.git $HOME/coding/st
+git clone https://github.com/bcmertz/st.git $HOME/coding/st || warn "failed to clone st"
 cd $HOME/coding/st
-sudo make clean install
+sudo make clean install || warn "failed to install st"
 cd $HOME
 
 # setup passwords
@@ -42,24 +45,25 @@ while [ true ] ; do
         exit
     fi
 done
-git clone https://github.com/bcmertz/passwords.git
+git clone https://github.com/bcmertz/passwords.git || warn "failed to download passwords"
+setuppass || warn "failed to setup gpg / passwords"
 
 # use our local passmenu
 sudo rm /usr/bin/passenu
 
 # setup crons
-crontab $HOME/.local/bin/cron/crontabbackup.txt
-sudo systemctl enable --now cronie.service
+crontab $HOME/.local/bin/cron/crontabbackup.txt || warn "failed to create setup cron"
+sudo systemctl enable --now cronie.service  || warn "failed to enable cron service"
 
 # TODO: setupUFW
 
 # TODO: config grub?
 
 # touchegg gestures
-sudo systemctl enable --now touchegg.service
+sudo systemctl enable --now touchegg.service || warn "failed to setup touchegg service"
 
 # printing
-sudo systemctl enable --now cups.socket
+sudo systemctl enable --now cups.socket || warn "failed to setup printing service"
 
 # fonts
-fc-cache -f -v
+fc-cache -f -v || warn "failed to regenerate font cache"
